insert into players(player_id,team_id,player_name,position) values (1,1,"Thibaut Courtois", "GK");
UPDATE players SET nationality = "Belgium" WHERE player_id = 1;
insert into players(player_id,team_id,player_name,position) values (2,1,"Eder Militao", "CB");
UPDATE players SET nationality = "Brazil" WHERE player_id = 2;
insert into players(player_id,team_id,player_name,position) values (3,1,"David Alaba", "CB");
UPDATE players SET nationality = "Austria" WHERE player_id = 3;
insert into players(player_id,team_id,player_name,position) values (4,1,"Ferland Mendy", "LB");
UPDATE players SET nationality = "France" WHERE player_id = 4;
insert into players(player_id,team_id,player_name,position) values (5,1,"Miguel Gutierrez", "LB");
UPDATE players SET nationality = "Spain" WHERE player_id = 5;
insert into players(player_id,team_id,player_name,position) values (6,1,"Daniel Carvajal", "RB");
UPDATE players SET nationality = "Spain" WHERE player_id = 6;
insert into players(player_id,team_id,player_name,position) values (7,1,"Lucas Vazquez", "RB");
UPDATE players SET nationality = "Spain", player_name = "Lucas Vazquez" WHERE player_id = 7;
insert into players(player_id,team_id,player_name,position,nationality) values (8,1,"Nacho Fernandez", "CB","Spain");
insert into players(player_id,team_id,player_name,position,nationality) values (9,1,"Jesus Vallejo", "CB","Spain");
insert into players(player_id,team_id,player_name,position,nationality) values (10,1,"Marcelo", "LB","Brazil");
insert into players(player_id,team_id,player_name,position,nationality) values (11,1,"Federico Valverde", "CM","Uruguay");
insert into players(player_id,team_id,player_name,position,nationality) values (12,1,"Eduardo Camavinga", "CM","France");
insert into players(player_id,team_id,player_name,position,nationality) values (13,1,"Casemiro", "DM","Brasil");
update players set nationality = "Brazil" where player_id = 13;
insert into players(player_id,team_id,player_name,position,nationality) values (14,1,"Toni Kroos", "CM","Germany");
insert into players(player_id,team_id,player_name,position,nationality) values (15,1,"Luka Modric", "CM","Croatia");
insert into players(player_id,team_id,player_name,position,nationality) values (16,1,"Dani Ceballos", "CM","Spain");
insert into players(player_id,team_id,player_name,position,nationality) values (17,1,"Antonio Blanco", "CM","Spain");
insert into players(player_id,team_id,player_name,position,nationality) values (18,1,"Vinicius Junior", "LW","Brazil");
insert into players(player_id,team_id,player_name,position,nationality) values (19,1,"Rodrygo", "RW","Brazil");
insert into players(player_id,team_id,player_name,position,nationality) values (20,1,"Marco Asensio", "RW","Spain");
insert into players(player_id,team_id,player_name,position,nationality) values (21,1,"Karim Benzema", "CF","France");
insert into players(player_id,team_id,player_name,position,nationality) values (22,1,"Luka Jović", "CF","Serbia");
insert into players(player_id,team_id,player_name,position,nationality) values (23,1,"Mariano Díaz", "CF","Spain");
insert int1 players(player_id,team_id,player_name,position,nationality) values (24,1,"Eden Hazard", "LW","Belgium");
insert into players(player_id,team_id,player_name,position,nationality) values (25,1,"Gareth Bale", "RW","Wales");
